# Generated by Django 4.1.4 on 2022-12-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoninfo',
            name='Evolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution', to='pokemon.pokemonevolution'),
        ),
    ]
